-- 코드를 입력하세요
-- SELECT *
-- FROM (SELECT F.FLAVOR, SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL
--     FROM FIRST_HALF F RIGHT OUTER JOIN JULY J
--     ON F.SHIPMENT_ID = J.SHIPMENT_ID
--     GROUP BY J.FLAVOR
--     ORDER BY TOTAL DESC) T
-- WHERE ROWNUM <= 3;

-- SELECT *
-- FROM FIRST_HALF F RIGHT OUTER JOIN JULY J
-- ON F.SHIPMENT_ID = J.SHIPMENT_ID

SELECT J.FLAVOR
FROM FIRST_HALF F RIGHT OUTER JOIN JULY J
ON F.SHIPMENT_ID = J.SHIPMENT_ID
GROUP BY J.FLAVOR
ORDER BY SUM(NVL(F.TOTAL_ORDER, 0) + NVL(J.TOTAL_ORDER, 0)) DESC
FETCH FIRST 3 ROW ONLY;