WITH HOURS AS (
    SELECT LEVEL - 1 AS HOUR
    FROM dual
    CONNECT BY LEVEL <= 24
)
SELECT H.HOUR AS HOUR, COUNT(A.DATETIME) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
ON H.HOUR = EXTRACT(HOUR FROM CAST(A.DATETIME AS TIMESTAMP))
GROUP BY H.HOUR
ORDER BY H.HOUR