-- 코드를 입력하세요
SELECT DISTINCT HOUR AS HOUR, COUNT(HOUR) AS COUNT
FROM (SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP)) AS HOUR
    FROM ANIMAL_OUTS
    WHERE TO_CHAR(DATETIME, 'HH24') >= '09'
    AND TO_CHAR(DATETIME, 'HH24') < '20'
    -- GROUP BY DATETIME)
      )
GROUP BY HOUR
ORDER BY HOUR